#ifndef UNIVERSAL_H
#define UNIVERSAL_H
#define DEFAULT_MODE 0644
#define SUCCESS 0
#define FAILURE -1
#define NOT_FOUND 1
#define ALREADY_AVAL 2
#define INVALID_CHOICE 3
#define BOOK_ALREADY_BORROWED 4
#define BOOK_NOT_BORROWED 5
#endif